/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const aws = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-1:1f1eced4-bdd8-45c0-8c5a-945bcc3afc6c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_yWUxaON7o",
    "aws_user_pools_web_client_id": "h3i5nh79sgt27ql9jq0c2rs3a",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://jbxlzfvmengxhnan66xcjp5p64.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qrg33pd75jfhrfddspex5n5cr4",
    "aws_user_files_s3_bucket": "v04sevenaware9dabe40ed40e4a24b0a8b3db13deb9ab194842-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default aws;
